<?php

namespace Webservices\ApiBundle\Repository;

use JMS\Serializer\SerializerInterface;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends \Doctrine\ORM\EntityRepository
{

    public function getConvertRate($initialCurrencyCode, $targetCurrencyCode)
    {
        // Get selected items :
        $initialCurrency = $this->findOneBy(array('isoCode' => $initialCurrencyCode));
        $targetCurrency = $this->findOneBy(array('isoCode' => $targetCurrencyCode));

        // Get rate :
        $rate = 1 / $initialCurrency->getRate() * $targetCurrency->getRate();

        // Return final amount :
        return $rate;
    }

    public function getConvertedAmount($initialCurrencyCode, $targetCurrencyCode, $amount)
    {
        // Use previous function to get rate :
        $rate = $this->getConvertRate($initialCurrencyCode, $targetCurrencyCode);

        // Multiply by amount and return value :
        return $rate * $amount;
    }

    public function getCurrencyList() {
        $list = $this->findAll();
       return $list;
    }
}
